deployment:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
  resources: {}
  args:
    containerPort: 4000
  securityContext: # Set on container level
    runAsUser: 2000
    allowPrivilegeEscalation: false
  strategy: {} # Read more: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  nodeSelector: {}

