// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	"github.com/kyma-incubator/compass/components/director/pkg/graphql/externalschema"
	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-incubator/compass/components/director/internal/model"
)

// BusinessTenantMappingConverter is an autogenerated mock type for the BusinessTenantMappingConverter type
type BusinessTenantMappingConverter struct {
	mock.Mock
}

// MultipleToGraphQL provides a mock function with given fields: in
func (_m *BusinessTenantMappingConverter) MultipleToGraphQL(in []*model.BusinessTenantMapping) []*externalschema.Tenant {
	ret := _m.Called(in)

	var r0 []*externalschema.Tenant
	if rf, ok := ret.Get(0).(func([]*model.BusinessTenantMapping) []*externalschema.Tenant); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*externalschema.Tenant)
		}
	}

	return r0
}
