// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	"github.com/kyma-incubator/compass/components/director/pkg/graphql/externalschema"
)
import mock "github.com/stretchr/testify/mock"
import model "github.com/kyma-incubator/compass/components/director/internal/model"

// Converter is an autogenerated mock type for the Converter type
type Converter struct {
	mock.Mock
}

// RequestInputFromGraphQL provides a mock function with given fields: in
func (_m *Converter) RequestInputFromGraphQL(in externalschema.PackageInstanceAuthRequestInput) model.PackageInstanceAuthRequestInput {
	ret := _m.Called(in)

	var r0 model.PackageInstanceAuthRequestInput
	if rf, ok := ret.Get(0).(func(externalschema.PackageInstanceAuthRequestInput) model.PackageInstanceAuthRequestInput); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Get(0).(model.PackageInstanceAuthRequestInput)
	}

	return r0
}

// SetInputFromGraphQL provides a mock function with given fields: in
func (_m *Converter) SetInputFromGraphQL(in externalschema.PackageInstanceAuthSetInput) (model.PackageInstanceAuthSetInput, error) {
	ret := _m.Called(in)

	var r0 model.PackageInstanceAuthSetInput
	if rf, ok := ret.Get(0).(func(externalschema.PackageInstanceAuthSetInput) model.PackageInstanceAuthSetInput); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Get(0).(model.PackageInstanceAuthSetInput)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(externalschema.PackageInstanceAuthSetInput) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ToGraphQL provides a mock function with given fields: in
func (_m *Converter) ToGraphQL(in *model.PackageInstanceAuth) (*externalschema.PackageInstanceAuth, error) {
	ret := _m.Called(in)

	var r0 *externalschema.PackageInstanceAuth
	if rf, ok := ret.Get(0).(func(*model.PackageInstanceAuth) *externalschema.PackageInstanceAuth); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*externalschema.PackageInstanceAuth)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.PackageInstanceAuth) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
