// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	"github.com/kyma-incubator/compass/components/director/pkg/graphql/externalschema"
	mock "github.com/stretchr/testify/mock"

	model "github.com/kyma-incubator/compass/components/director/internal/model"
)

// RuntimeConverter is an autogenerated mock type for the RuntimeConverter type
type RuntimeConverter struct {
	mock.Mock
}

// InputFromGraphQL provides a mock function with given fields: in
func (_m *RuntimeConverter) InputFromGraphQL(in externalschema.RuntimeInput) model.RuntimeInput {
	ret := _m.Called(in)

	var r0 model.RuntimeInput
	if rf, ok := ret.Get(0).(func(externalschema.RuntimeInput) model.RuntimeInput); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Get(0).(model.RuntimeInput)
	}

	return r0
}

// MultipleToGraphQL provides a mock function with given fields: in
func (_m *RuntimeConverter) MultipleToGraphQL(in []*model.Runtime) []*externalschema.Runtime {
	ret := _m.Called(in)

	var r0 []*externalschema.Runtime
	if rf, ok := ret.Get(0).(func([]*model.Runtime) []*externalschema.Runtime); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*externalschema.Runtime)
		}
	}

	return r0
}

// ToGraphQL provides a mock function with given fields: in
func (_m *RuntimeConverter) ToGraphQL(in *model.Runtime) *externalschema.Runtime {
	ret := _m.Called(in)

	var r0 *externalschema.Runtime
	if rf, ok := ret.Get(0).(func(*model.Runtime) *externalschema.Runtime); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*externalschema.Runtime)
		}
	}

	return r0
}
