// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	"github.com/kyma-incubator/compass/components/director/pkg/graphql/externalschema"
)
import mock "github.com/stretchr/testify/mock"
import model "github.com/kyma-incubator/compass/components/director/internal/model"

// ApplicationConverter is an autogenerated mock type for the ApplicationConverter type
type ApplicationConverter struct {
	mock.Mock
}

// CreateInputFromGraphQL provides a mock function with given fields: in
func (_m *ApplicationConverter) CreateInputFromGraphQL(in externalschema.ApplicationRegisterInput) (model.ApplicationRegisterInput, error) {
	ret := _m.Called(in)

	var r0 model.ApplicationRegisterInput
	if rf, ok := ret.Get(0).(func(externalschema.ApplicationRegisterInput) model.ApplicationRegisterInput); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Get(0).(model.ApplicationRegisterInput)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(externalschema.ApplicationRegisterInput) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GraphQLToModel provides a mock function with given fields: obj, tenantID
func (_m *ApplicationConverter) GraphQLToModel(obj *externalschema.Application, tenantID string) *model.Application {
	ret := _m.Called(obj, tenantID)

	var r0 *model.Application
	if rf, ok := ret.Get(0).(func(*externalschema.Application, string) *model.Application); ok {
		r0 = rf(obj, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Application)
		}
	}

	return r0
}

// MultipleToGraphQL provides a mock function with given fields: in
func (_m *ApplicationConverter) MultipleToGraphQL(in []*model.Application) []*externalschema.Application {
	ret := _m.Called(in)

	var r0 []*externalschema.Application
	if rf, ok := ret.Get(0).(func([]*model.Application) []*externalschema.Application); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*externalschema.Application)
		}
	}

	return r0
}

// ToGraphQL provides a mock function with given fields: in
func (_m *ApplicationConverter) ToGraphQL(in *model.Application) *externalschema.Application {
	ret := _m.Called(in)

	var r0 *externalschema.Application
	if rf, ok := ret.Get(0).(func(*model.Application) *externalschema.Application); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*externalschema.Application)
		}
	}

	return r0
}

// UpdateInputFromGraphQL provides a mock function with given fields: in
func (_m *ApplicationConverter) UpdateInputFromGraphQL(in externalschema.ApplicationUpdateInput) model.ApplicationUpdateInput {
	ret := _m.Called(in)

	var r0 model.ApplicationUpdateInput
	if rf, ok := ret.Get(0).(func(externalschema.ApplicationUpdateInput) model.ApplicationUpdateInput); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Get(0).(model.ApplicationUpdateInput)
	}

	return r0
}
