// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	"github.com/kyma-incubator/compass/components/director/pkg/graphql/externalschema"
)
import mock "github.com/stretchr/testify/mock"

// AppConverter is an autogenerated mock type for the AppConverter type
type AppConverter struct {
	mock.Mock
}

// CreateInputGQLToJSON provides a mock function with given fields: in
func (_m *AppConverter) CreateInputGQLToJSON(in *externalschema.ApplicationRegisterInput) (string, error) {
	ret := _m.Called(in)

	var r0 string
	if rf, ok := ret.Get(0).(func(*externalschema.ApplicationRegisterInput) string); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*externalschema.ApplicationRegisterInput) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
