// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import (
	"github.com/kyma-incubator/compass/components/director/pkg/graphql/externalschema"
)
import mock "github.com/stretchr/testify/mock"
import model "github.com/kyma-incubator/compass/components/director/internal/model"

// ApplicationTemplateConverter is an autogenerated mock type for the ApplicationTemplateConverter type
type ApplicationTemplateConverter struct {
	mock.Mock
}

// ApplicationFromTemplateInputFromGraphQL provides a mock function with given fields: in
func (_m *ApplicationTemplateConverter) ApplicationFromTemplateInputFromGraphQL(in externalschema.ApplicationFromTemplateInput) model.ApplicationFromTemplateInput {
	ret := _m.Called(in)

	var r0 model.ApplicationFromTemplateInput
	if rf, ok := ret.Get(0).(func(externalschema.ApplicationFromTemplateInput) model.ApplicationFromTemplateInput); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Get(0).(model.ApplicationFromTemplateInput)
	}

	return r0
}

// InputFromGraphQL provides a mock function with given fields: in
func (_m *ApplicationTemplateConverter) InputFromGraphQL(in externalschema.ApplicationTemplateInput) (model.ApplicationTemplateInput, error) {
	ret := _m.Called(in)

	var r0 model.ApplicationTemplateInput
	if rf, ok := ret.Get(0).(func(externalschema.ApplicationTemplateInput) model.ApplicationTemplateInput); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Get(0).(model.ApplicationTemplateInput)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(externalschema.ApplicationTemplateInput) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MultipleToGraphQL provides a mock function with given fields: in
func (_m *ApplicationTemplateConverter) MultipleToGraphQL(in []*model.ApplicationTemplate) ([]*externalschema.ApplicationTemplate, error) {
	ret := _m.Called(in)

	var r0 []*externalschema.ApplicationTemplate
	if rf, ok := ret.Get(0).(func([]*model.ApplicationTemplate) []*externalschema.ApplicationTemplate); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*externalschema.ApplicationTemplate)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]*model.ApplicationTemplate) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ToGraphQL provides a mock function with given fields: in
func (_m *ApplicationTemplateConverter) ToGraphQL(in *model.ApplicationTemplate) (*externalschema.ApplicationTemplate, error) {
	ret := _m.Called(in)

	var r0 *externalschema.ApplicationTemplate
	if rf, ok := ret.Get(0).(func(*model.ApplicationTemplate) *externalschema.ApplicationTemplate); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*externalschema.ApplicationTemplate)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.ApplicationTemplate) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
